# Generated by Django 5.1.2 on 2024-11-04 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Network_performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('bad', 'Bad')], default='good', max_length=200)),
                ('download_speed', models.FloatField(help_text='Download speed in Mbps')),
                ('upload_speed', models.FloatField(help_text='upload speed in Mbps')),
                ('latency_speed', models.FloatField(help_text='Latency speed in milliseconds')),
                ('uptime', models.FloatField(help_text='Uptime percentage (0-100%)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Network Performance',
                'verbose_name_plural': 'Network Performances',
            },
        ),
    ]
