# Generated by Django 5.1.2 on 2024-10-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePlanManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default='Basic Plan', max_length=200)),
                ('speed', models.PositiveIntegerField(default=0, help_text='Speed in Mbps')),
                ('data_limit', models.PositiveIntegerField(default=0, help_text='Data limit in GB')),
                ('price', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('description', models.TextField(blank=True, max_length=200)),
            ],
        ),
    ]
