# Generated by Django 5.1.2 on 2024-10-22 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internet_service_plan_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceplanmanagement',
            options={'verbose_name': 'Service Plan', 'verbose_name_plural': 'Service Plans'},
        ),
    ]
