# Generated by Django 5.1.2 on 2024-11-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_service_plan_management', '0002_alter_serviceplanmanagement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceplanmanagement',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('canceled', 'Canceled')], default='inactive', max_length=200),
        ),
    ]
