# Generated by Django 5.1.2 on 2024-11-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_service_plan_management', '0003_serviceplanmanagement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplanmanagement',
            name='data_limit',
            field=models.PositiveIntegerField(help_text='Data limit in GB'),
        ),
        migrations.AlterField(
            model_name='serviceplanmanagement',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='serviceplanmanagement',
            name='speed',
            field=models.PositiveIntegerField(help_text='Speed in Mbps'),
        ),
    ]
