# Generated by Django 5.1.2 on 2024-10-22 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internet_service_plan_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('canceled', 'Canceled')], default='inactive', max_length=200)),
                ('service_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internet_service_plan_management.serviceplanmanagement')),
            ],
        ),
    ]
