# Generated by Django 5.1.2 on 2024-11-04 09:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_subscription_management', '0002_alter_customer_profile_options_and_more'),
        ('internet_service_plan_management', '0003_serviceplanmanagement_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('service_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internet_service_plan_management.serviceplanmanagement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Subscription',
                'verbose_name_plural': 'Customer Subscriptions',
            },
        ),
        migrations.DeleteModel(
            name='Customer_profile',
        ),
    ]
